site_name: Wiki
site_url: https://mydomain.org/mysite
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  font:
    text: Afacad Flux 
    code: Red Hat Mono
  
  palette:
  # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange



  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.
  
nav:
  - Home: index.md
  - About:
    - About The Project: about/about.md
  - Github Codeexamples:
    - Github Codeexamples: docs\GithubCodeexamples\GithubCodeexamples.md
  - General Directives:
    - Guide to Best-Practice Application Patterns: docs\Anvisninger\Generelt\AnvisningerGenerelt.md
    - Guide to Best-Practice Directives: docs\Anvisninger\Generelt\VejledningGenerelt.md
  - Directives SDI:
    - Document Object: docs\Anvisninger\SDI\AnvisningerDokumentobjektetSagsDokumentobjekt.md
    - Case Object: docs\Anvisninger\SDI\AnvisningerSagsObjekt.md
  - Directives YDI:
    - Grant (Bevillings) Object: docs\Anvisninger\YDI\AnvisningerBevillingsobjekt.md
    - Economic Effectuation (Økonomisk Effektuerings) Object: docs\Anvisninger\YDI\AnvisningerOekonomiskEffektueringsobjektet.md